# Generated by Django 5.0.6 on 2025-05-14 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_is_approaved_by_admin_client_is_deliveryman'),
        ('delivery', '0002_rename_locationupdate_locationhistory_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credits',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='credits', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_order', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_man',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_man', to='clients.client'),
        ),
    ]
