# Generated by Django 5.0.6 on 2025-05-13 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_approaved_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_deliveryman',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='national_id_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='vehicle',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
