# Generated by Django 5.0.6 on 2025-05-17 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_approaved_by_admin_user_is_deliveryman_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_restaurant',
            field=models.BooleanField(default=False),
        ),
    ]
