# Generated by Django 5.0.6 on 2025-05-14 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0002_client_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="is_approaved_by_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="client",
            name="is_deliveryman",
            field=models.BooleanField(default=False),
        ),
    ]
