# Generated by Django 5.0.6 on 2025-05-14 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_is_approaved_by_admin_client_is_deliveryman'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='address',
            new_name='address_current',
        ),
        migrations.AddField(
            model_name='client',
            name='address_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='address_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
